/**
 * How wide a string is in Montserrat, and which byte each character becomes.
 *
 * The PDF writer lays a table out before it draws it — sizing columns, right-aligning
 * numbers, truncating the address that will not fit — so it has to know the width of every
 * glyph it can emit. Those widths live in `montserrat.ts`, generated by
 * `scripts/build-montserrat.mjs` from the font programme the PDF embeds, so the numbers
 * the layout measures with and the outlines the viewer draws come from the same file and
 * cannot disagree. They are indexed by WinAnsi code from 32, in units of 1/1000 em, so the
 * width of a string at 9pt is `sum(widths) * 9 / 1000`.
 *
 * WHY WINANSI STILL. Until 9 September this file measured Helvetica, one of the fourteen
 * faces every viewer supplies, and the one-byte encoding was the price of embedding nothing.
 * Montserrat is embedded, so a two-byte encoding would be possible — but the writer's whole
 * repertoire is tables of addresses, names, stages and dates, WinAnsi covers all of it, and
 * one byte per character keeps the content stream, the width table and this file simple.
 * The `?` for anything outside it (below) is still the honest answer, and still the same
 * one point where the measured width and the drawn bytes are guaranteed to agree.
 *
 * The five zeroes in each table are the codes CP1252 leaves undefined (0x81, 0x8D, 0x8F,
 * 0x90, 0x9D) and DEL. `encode` below can never produce them, and `widthOf` treats a zero
 * as unencodable for the same reason.
 */
import { REGULAR as REGULAR_FACE, SEMIBOLD } from "./montserrat";

const REGULAR = REGULAR_FACE.widths;
/** "Bold" in the writers' vocabulary is Montserrat SemiBold — see build-montserrat.mjs. */
const BOLD = SEMIBOLD.widths;

/**
 * The characters WinAnsi puts in 0x80–0x9F, which Latin-1 leaves empty. All eight of the
 * ones this app actually produces are in here — the em dash the tables use for "no
 * answer", the middle dot in "1042 · Pre-construction", and the curly quotes and
 * ellipsis that arrive in text pasted from Word.
 */
const HIGH: Record<string, number> = {
  "€": 0x80, "‚": 0x82, "ƒ": 0x83, "„": 0x84, "…": 0x85,
  "†": 0x86, "‡": 0x87, "ˆ": 0x88, "‰": 0x89, "Š": 0x8a,
  "‹": 0x8b, "Œ": 0x8c, "Ž": 0x8e, "‘": 0x91, "’": 0x92,
  "“": 0x93, "”": 0x94, "•": 0x95, "–": 0x96, "—": 0x97,
  "˜": 0x98, "™": 0x99, "š": 0x9a, "›": 0x9b, "œ": 0x9c,
  "ž": 0x9e, "Ÿ": 0x9f
};

const QUESTION = 0x3f;

/**
 * One WinAnsi byte per character, with `?` for anything the encoding cannot carry.
 *
 * A `?` is the honest answer here and a mojibake box is not: the embedded subset holds
 * WinAnsi's 218 characters and there is no arrangement of them that spells a Chinese
 * name. Anything outside WinAnsi — and anything whose glyph is absent, which is what a
 * zero width means — becomes `?` at this one point, so the width the layout measured and
 * the bytes the page carries can never disagree.
 */
export function encode(text: string, bold = false): number[] {
  const widths = bold ? BOLD : REGULAR;
  const out: number[] = [];
  for (const ch of text) {
    const code = ch.codePointAt(0)!;
    let byte =
      code >= 0x20 && code <= 0x7e ? code
      : code >= 0xa0 && code <= 0xff ? code
      : (HIGH[ch] ?? QUESTION);
    // A no-break space and a soft hyphen both have metrics, but a tab, a newline or a
    // NUL inside a table cell is a layout accident rather than a character; they become
    // spaces so a pasted multi-line note stays on one row.
    if (code < 0x20) byte = 0x20;
    // Belt and braces, and it holds nothing up today: every byte the two branches above
    // can produce has a width. It is here because the one way to break that is to add a
    // character to `HIGH` whose glyph Montserrat lacks — and a zero width is invisible,
    // since the character still draws as nothing while the layout reserves no room for
    // it and the rest of the row shifts left. `export-check` asserts the property.
    if (!widths[byte - 32]) byte = QUESTION;
    out.push(byte);
  }
  return out;
}

/** Width of already-encoded bytes, in points. */
export function widthOfBytes(bytes: number[], size: number, bold = false): number {
  const widths = bold ? BOLD : REGULAR;
  let units = 0;
  for (const b of bytes) units += widths[b - 32] ?? 0;
  return (units * size) / 1000;
}

export function widthOf(text: string, size: number, bold = false): number {
  return widthOfBytes(encode(text, bold), size, bold);
}

/**
 * `text` shortened to fit `max` points, with an ellipsis if anything came off.
 *
 * Measured against the same tables the drawing uses, so a truncated cell is guaranteed
 * to fit rather than nearly fit — this is what stops the Address column writing over the
 * Stage column. An ellipsis, not a hard cut: "12 Hawthorn Cres" and "12 Hawthorn Cr…"
 * are different claims about an address.
 */
export function truncate(text: string, max: number, size: number, bold = false): string {
  if (widthOf(text, size, bold) <= max) return text;
  const ellipsis = "…";
  const room = max - widthOf(ellipsis, size, bold);
  if (room <= 0) return "";
  const chars = [...text];
  let width = 0;
  let taken = 0;
  while (taken < chars.length) {
    const next = widthOf(chars[taken], size, bold);
    if (width + next > room) break;
    width += next;
    taken++;
  }
  return chars.slice(0, taken).join("").trimEnd() + ellipsis;
}
