-- =============================================================================
-- 0073 — job numbers are three digits, from 001
-- =============================================================================
-- Amber, 31 August: "what happens when we have over 99 jobs on a project or over 9999
-- projects, will it auto increment" — and then, on the answer: "can you adjust job
-- numbers (existing and new) now so they are all three digits and start at 001 … we can
-- have over 100 jobs on a project."
--
-- ------------------------------------------------------------ what was actually wrong
-- Projects auto-increment and always did. `project_id` is `integer generated by default
-- as identity (start with 1000)` with a floor of 1000 and no ceiling, so 9999 is followed
-- by 10000 and jobs on it read `10001-001`. Nothing in the app parses a project number.
-- Watched on a replayed database: the sequence pushed to 9999, three projects taken.
--
-- Jobs did not. The hundredth job on a project was refused outright:
--
--   NOTICE:  job #100 FAILED: duplicate key value violates unique constraint "jobs_pkey"
--   NOTICE:  jobs created: 99, high-water: 99
--
-- `assign_job_sequence()` formatted the number as `lpad(next_no::text, 2, '0')`, and
-- **lpad is a pad AND a fit**: `lpad('100', 2, '0')` is `'10'`, not `'100'`. So job 100
-- was handed the sequence job 10 already held, `job_id` came out as an existing
-- '1042-10', and the primary key refused it.
--
-- The refusal is the good half. `job_id` IS the key, so the collision could not silently
-- produce two builds sharing a number across contracts, folders and invoices — the exact
-- accident the high-water mark in 0028 exists to prevent. What it did instead was cap a
-- project at 99 jobs and report it as a duplicate-key error naming no cause.
--
-- ------------------------------------------------------- why three digits, and why now
-- The narrow fix is to keep two digits below 100 and write 100 upwards plainly. That was
-- written, and Amber overruled it, correctly: a project of 30 lots is already ordinary
-- here (1006 has 30 today) and land divisions run past 100, so `1042-99` followed by
-- `1042-100` is a convention that changes width halfway through one project's own list.
-- Three digits from the start is one shape for every job, and it sorts as text — which
-- is how the board, the table and every export order them. That text sort holds to 999
-- and would misorder past it ('1000' sorts before '999'), which is true of any fixed
-- width and is four times further out than the widest division Lofty has ever run.
--
-- Renumbering existing jobs is normally the thing this schema refuses. 0028 says a job
-- number is assigned once and never regenerated, *because it goes on contracts*. That
-- reasoning is about numbers that have left the building. Today's 66 jobs were created
-- in this app in the last few days, before the import, and none of them is on a contract
-- or a SharePoint folder anybody has filed against. This is the last moment the change
-- is free, which is why it is being made now rather than argued about later.
--
-- All nine foreign keys into `jobs(job_id)` are ON UPDATE CASCADE — activity_events,
-- address_history, comments, document_links, job_pipeline_positions, job_stage_events,
-- taggings, tasks, variations — checked against the live database before writing this,
-- so the renumber carries every child with it. `jobs_resync_job_id` (BEFORE UPDATE)
-- rebuilds `job_id` from the parts, and the CHECK that they agree keeps it honest.
--
-- WHAT DOES NOT CHANGE
--
--   Gaps stay permanent and a number is never reissued: the high-water mark is a count,
--   untouched by how it is formatted. Project 1006 sits at 30 and its next job is 031.
--
--   `job_number_old` — the SiteBook and Trello number — is not touched. It is what the
--   old system called the job, and it is not ours to reformat.
--
--   The remaining ceiling is `project_job_seq_high_water`, a smallint: 32767 jobs on one
--   project. Four orders of magnitude past any land division.
-- =============================================================================

-- ------------------------------------------------------ new jobs: 001, and never wider
create or replace function assign_job_sequence() returns trigger
language plpgsql set search_path = public, pg_temp as $$
declare
  next_no integer;
begin
  if new.job_sequence is null then
    -- Allocated from a high-water mark on the parent, not from max() over the live jobs.
    --
    -- max()+1 looks equivalent and is not: delete the HIGHEST job and the next insert
    -- reissues its number. A gap is fine and expected — the design says gaps are
    -- permanent — but reissuing a retired number is strictly worse, because two
    -- different builds then share '1042-003' across contracts, folders and invoices.
    --
    -- The UPDATE takes a row lock on the parent, which is also what stops two people
    -- creating jobs on the same project at once from both claiming the same number.
    update projects
       set project_job_seq_high_water = project_job_seq_high_water + 1
     where project_id = new.project_id
    returning project_job_seq_high_water into next_no;

    if next_no is null then
      raise exception 'project % does not exist', new.project_id using errcode = '23503';
    end if;

    -- Pad to three, never truncate. lpad() does both, and the second half of that is
    -- what capped a project at 99 jobs when this padded to two.
    new.job_sequence := case
      when next_no < 1000 then lpad(next_no::text, 3, '0')
      else next_no::text
    end;
  end if;

  new.job_id := new.project_id::text || '-' || new.job_sequence;
  return new;
end $$;

comment on function assign_job_sequence() is
  'Issues a job its number from the parent''s high-water mark, under a row lock so two people creating jobs at once cannot collide. Zero-padded to three digits — 001 — and written plainly past 999 (0073). Gaps are permanent and a number is never reissued: it goes on contracts.';

-- --------------------------------------------------------- existing jobs: 01 becomes 001
-- One statement. `jobs_resync_job_id` rebuilds job_id from the parts, and every child
-- follows by ON UPDATE CASCADE. Jobs already three digits or wider are left alone, so
-- this is safe to replay.
-- The case is planted BEFORE the statement that fixes it, so the statement below is what
-- has to do the work. Two earlier shapes of this proof both passed with the renumber
-- deleted: the first asserted "none are left short" on a replayed database where no job
-- exists yet, and the second planted a job and then ran its OWN copy of the UPDATE. Both
-- were watched passing with the real statement removed, which is the only reason they
-- were not shipped. The project number is handed between the blocks through a session
-- setting, since a DO block returns nothing.
do $$
declare
  a  uuid;
  me uuid;
  p  integer;
  seq text;
  s_last bigint;
  s_called boolean;
begin
  select profile_id into me from profiles limit 1;
  if me is null then
    perform set_config('lofty.renumber_probe', '', false);
    raise notice 'no profile to author the renumber probe with — skipped';
    return;
  end if;

  seq := pg_get_serial_sequence('projects', 'project_id');
  execute format('select last_value, is_called from %s', seq) into s_last, s_called;
  perform set_config('lofty.renumber_seq_last', s_last::text, false);
  perform set_config('lofty.renumber_seq_called', s_called::text, false);

  insert into addresses (address_lot_number, address_street_1, address_suburb,
                         address_state, address_postcode, address_council)
  values ('1', 'Renumber Street', 'Golden Grove', 'SA', '5125', 'City of Tea Tree Gully')
  returning address_id into a;
  insert into projects (project_original_address_id, project_current_address_id,
                        project_type, project_created_by)
  values (a, a, 'residential', me) returning project_id into p;

  -- The old shape, set by hand: what all 66 jobs in the live database look like right
  -- now, and what no job will be able to look like once the constraint below exists.
  insert into jobs (project_id, job_sequence, job_original_address_id,
                    job_current_address_id, job_owning_team, job_created_by)
  values (p, '07', a, a, 'acquisition_development', me);
  insert into tasks (job_id, task_name) values (p::text || '-07', 'A task that must follow');

  perform set_config('lofty.renumber_probe', p::text, false);
  perform set_config('lofty.renumber_address', a::text, false);
end $$;

-- --------------------------------------------------- existing jobs: 01 becomes 001
-- One statement. `jobs_resync_job_id` rebuilds job_id from the parts, and every child
-- follows by ON UPDATE CASCADE — all nine of them, checked against the live database
-- before this was written. Jobs already three digits or wider are left alone, so this is
-- safe to replay.
update jobs
   set job_sequence = lpad(job_sequence, 3, '0')
 where length(job_sequence) < 3;

do $$
declare
  p     integer;
  a     uuid;
  moved text;
  seq   text;
begin
  if coalesce(current_setting('lofty.renumber_probe', true), '') = '' then
    raise notice 'the renumber probe was skipped — nothing to assert';
    return;
  end if;
  p := current_setting('lofty.renumber_probe')::integer;
  a := current_setting('lofty.renumber_address')::uuid;

  if not exists (select 1 from jobs where job_id = p::text || '-007') then
    raise exception 'the renumber did not widen 07 to 007';
  end if;

  select job_id into moved from tasks where task_name = 'A task that must follow';
  if moved is distinct from p::text || '-007' then
    raise exception 'a child did not follow the rename: task points at %', coalesce(moved, '(null)');
  end if;

  delete from projects where project_id = p;
  delete from addresses where address_id = a;
  seq := pg_get_serial_sequence('projects', 'project_id');
  perform setval(seq,
                 current_setting('lofty.renumber_seq_last')::bigint,
                 current_setting('lofty.renumber_seq_called')::boolean);

  raise notice 'ok  an existing 07 became 007, and its task followed';
end $$;

-- ---------------------------------------------- and the shape becomes a guarantee
-- Found by `verify/check.sh`, which is the point of it. Its duplicate-sequence probe
-- inserts job_sequence '02' on a project that already has one and expects the unique
-- constraint to refuse it — and after the renumber it did not, because the job is '002'
-- now and '02' is a free value. The probe reported:
--
--   FAIL: duplicate job_sequence within a project accepted
--
-- The probe was right about the schema and not just about itself: '02' and '002' both
-- satisfy the old CHECK (digits, at least 1) and would have sat on the same project as
-- two different jobs that a person reads as the same number. Nothing in the app can do
-- that — job_sequence is omitted on every insert and written by the trigger — but the
-- import writes rows directly, and "the app would never" is not a constraint.
--
-- So the padding is enforced rather than merely produced: exactly three digits, or four
-- and more with no leading zero, which is what the trigger emits either side of 999.
alter table jobs drop constraint if exists jobs_sequence_is_padded;
alter table jobs add constraint jobs_sequence_is_padded
  check (job_sequence ~ '^[0-9]{3}$' or job_sequence ~ '^[1-9][0-9]{3,}$');

comment on column jobs.job_sequence is
  'The job''s number within its project — 001. Three digits since 0073, because a land division can run past 99 lots and a convention that changes width halfway through a project''s own list does not sort. Text, not an integer: it is half of a key that reads 1042-001, and it is padded. Past 999 it is written plainly.';

comment on column jobs.job_id is
  'The job number, 1042-001, as the primary key rather than a uuid with the number beside it — it is what people say out loud and what goes on contracts. Assigned at insert from the project number and the sequence and never regenerated afterwards; the one exception was 0073, which widened every existing job from two digits to three before any of them had left the building.';

-- ---------------------------------------------------------------------- proof
-- Four assertions, in the order somebody would doubt them: nothing is left two digits, a
-- child followed its parent's rename, a new job opens at 001, and the width holds at the
-- 999/1000 boundary.
--
-- THE PROBE PUTS THE PROJECT SEQUENCE BACK, AND THAT IS NOT TIDINESS
--
--   The first version of this block did not, and `verify/check.sh` refused it: the
--   throwaway project took number 1000, and behaviour.sql's second check is "project_id
--   starts at 1000" with its fourth hard-coding inserts against project 1000. So the
--   probe passed and broke the file that proves the numbering works —
--
--     ERROR:  project 1000 does not exist
--
--   A migration that consumes a project number also leaves a permanent gap in the series
--   people quote on contracts. The identity value is read before and restored after.
do $$
declare
  a          uuid;
  me         uuid;
  p          integer;
  stragglers integer;
  got        text[];
  seq        text;
  seq_last   bigint;
  seq_called boolean;
begin
  -- 1. Nothing anywhere is left short, and every job_id agrees with its parts. The
  --    renumber proved itself above; this is the whole-table sweep after it.
  select count(*) into stragglers from jobs where length(job_sequence) < 3;
  if stragglers > 0 then
    raise exception '% job(s) still carry a short sequence', stragglers;
  end if;

  if exists (select 1 from jobs where job_id <> project_id::text || '-' || job_sequence) then
    raise exception 'a job_id disagrees with its project number and sequence';
  end if;

  -- 2. A child followed. Referential integrity is the FK's job; what is worth asserting
  --    is that the cascade actually ran rather than the children being empty.
  if exists (
    select 1 from job_stage_events e
     where not exists (select 1 from jobs j where j.job_id = e.job_id)
  ) then
    raise exception 'a stage event points at a job number that no longer exists';
  end if;

  select profile_id into me from profiles limit 1;
  if me is null then
    raise notice 'no profile to author the probe with — the insert checks are skipped';
    return;
  end if;

  seq := pg_get_serial_sequence('projects', 'project_id');
  execute format('select last_value, is_called from %s', seq) into seq_last, seq_called;

  insert into addresses (address_lot_number, address_street_1, address_suburb,
                         address_state, address_postcode, address_council)
  values ('1', 'Three Digit Street', 'Golden Grove', 'SA', '5125', 'City of Tea Tree Gully')
  returning address_id into a;

  insert into projects (project_original_address_id, project_current_address_id,
                        project_type, project_created_by)
  values (a, a, 'residential', me)
  returning project_id into p;

  -- 3. A brand new project's first job opens at 001.
  insert into jobs (project_id, job_original_address_id, job_current_address_id,
                    job_owning_team, job_created_by)
  values (p, a, a, 'acquisition_development', me);

  if not exists (select 1 from jobs where job_id = p::text || '-001') then
    raise exception 'the first job on a new project did not open at 001';
  end if;

  -- 4. The boundary this migration is really about: 999, then the one that used to fail
  --    at 100, then one past the padding.
  update projects set project_job_seq_high_water = 98 where project_id = p;
  for i in 1..3 loop
    insert into jobs (project_id, job_original_address_id, job_current_address_id,
                      job_owning_team, job_created_by)
    values (p, a, a, 'acquisition_development', me);
  end loop;

  update projects set project_job_seq_high_water = 998 where project_id = p;
  for i in 1..2 loop
    insert into jobs (project_id, job_original_address_id, job_current_address_id,
                      job_owning_team, job_created_by)
    values (p, a, a, 'acquisition_development', me);
  end loop;

  select array_agg(job_sequence order by job_sequence::integer)
    into got from jobs where project_id = p;

  if got is distinct from array['001', '099', '100', '101', '999', '1000'] then
    raise exception 'the sequence reads wrong: %', got;
  end if;

  -- The project takes its jobs with it (jobs cascade from projects, 0028), then the
  -- number it borrowed goes back.
  delete from projects where project_id = p;
  delete from addresses where address_id = a;
  perform setval(seq, seq_last, seq_called);

  raise notice 'ok  every job is three digits from 001, and a project passes 99 and 999';
end $$;
