-- =============================================================================
-- 0073 — the hundredth job on a project
-- =============================================================================
-- Amber, 31 August: "what happens when we have over 99 jobs on a project or over 9999
-- projects, will it auto increment".
--
-- Projects do. `project_id` is `integer generated by default as identity (start with
-- 1000)` with a floor of 1000 and no ceiling, so 9999 is followed by 10000 and the job
-- numbers on it read `10001-01`. Nothing in the app parses the number, so a five-digit
-- project is a cosmetic change and not a breaking one. Watched, on a replayed database:
-- the sequence set to 9999, three projects taken, 9999 → 10000 → 10001.
--
-- Jobs did not. The hundredth job on a project was refused outright:
--
--   NOTICE:  job #100 FAILED: duplicate key value violates unique constraint "jobs_pkey"
--   NOTICE:  jobs created: 99, high-water: 99
--
-- WHY, AND IT IS ONE FUNCTION CALL
--
--   `assign_job_sequence()` formatted the number as `lpad(next_no::text, 2, '0')`, which
--   is right for 1..99 and wrong from 100 up, because **lpad truncates**. It is a pad
--   AND a fit: `lpad('100', 2, '0')` is `'10'`, not `'100'`. So job 100 was handed the
--   sequence already held by job 10, `job_id` came out as an existing '1042-10', and the
--   primary key refused it.
--
--   The failure is the good half. `job_id` is the key, so the collision could not
--   silently produce two builds sharing a number across contracts, folders and invoices
--   — which is the exact accident the high-water mark in 0028 exists to prevent. What it
--   did instead was cap a project at 99 jobs and report it as a duplicate-key error
--   naming no cause, on the hundredth insert of a batch.
--
--   Reachable in the ordinary way: MAX_SPLIT is 60 per batch, so two splits on a large
--   land division get there without anybody doing anything unusual.
--
-- WHAT THIS CHANGES, AND WHAT IT DELIBERATELY DOES NOT
--
--   Below 100 the format is untouched — '01' through '99', exactly as issued today. No
--   existing job number moves, and none can: they are on contracts, and 0028 is explicit
--   that a job number is assigned once and never regenerated. From 100 the number is
--   written plainly: '1042-100'.
--
--   The two-digit pad stays rather than widening to three ('001') for the same reason.
--   Renumbering every job that exists to make new ones line up in a column is the tail
--   wagging the dog.
--
--   `project_job_seq_high_water` is smallint, so the real ceiling is now 32767 jobs on
--   one project. Left alone: it is four orders of magnitude past any land division, and
--   widening a column to answer a question nobody has asked is how a schema grows.
-- =============================================================================

create or replace function assign_job_sequence() returns trigger
language plpgsql set search_path = public, pg_temp as $$
declare
  next_no integer;
begin
  if new.job_sequence is null then
    -- Allocated from a high-water mark on the parent, not from max() over the live jobs.
    --
    -- max()+1 looks equivalent and is not: delete the HIGHEST job and the next insert
    -- reissues its number. A gap is fine and expected — the design says gaps are
    -- permanent — but reissuing a retired number is strictly worse, because two
    -- different builds then share '1042-03' across contracts, folders and invoices.
    --
    -- The UPDATE takes a row lock on the parent, which is also what stops two people
    -- creating jobs on the same project at once from both claiming the same number.
    update projects
       set project_job_seq_high_water = project_job_seq_high_water + 1
     where project_id = new.project_id
    returning project_job_seq_high_water into next_no;

    if next_no is null then
      raise exception 'project % does not exist', new.project_id using errcode = '23503';
    end if;

    -- Pad to two, never truncate. lpad() does both, and the second half of that is what
    -- capped a project at 99 jobs: lpad('100', 2, '0') = '10'.
    new.job_sequence := case
      when next_no < 100 then lpad(next_no::text, 2, '0')
      else next_no::text
    end;
  end if;

  new.job_id := new.project_id::text || '-' || new.job_sequence;
  return new;
end $$;

comment on function assign_job_sequence() is
  'Issues a job its number from the parent''s high-water mark, under a row lock so two people creating jobs at once cannot collide. Zero-padded to two digits up to 99 and written plainly from 100 — 0073, where padding with lpad turned out to truncate and refuse the hundredth job on a project. Gaps are permanent and a number is never reissued: it goes on contracts.';

-- ---------------------------------------------------------------------- proof
-- Three jobs, not a hundred. The high-water mark is set to 98 on a throwaway project so
-- the next three inserts land exactly on the boundary this migration is about — 99, then
-- the one that used to fail, then one past it.
--
-- THE PROBE PUTS THE PROJECT SEQUENCE BACK, AND THAT IS NOT TIDINESS
--
--   The first version of this block did not, and `verify/check.sh` refused it: the
--   throwaway project took number 1000, and behaviour.sql's second check is "project_id
--   starts at 1000" with its fourth hard-coding job inserts against project 1000. So the
--   probe passed and broke the file that proves the numbering works —
--
--     ERROR:  project 1000 does not exist
--
--   A migration that consumes a project number leaves a permanent gap in the series
--   people quote on contracts, which is worth avoiding on its own. The identity value is
--   read before and restored after, so this migration costs the sequence nothing.
do $$
declare
  a          uuid;
  me         uuid;
  p          integer;
  got        text[];
  seq        text;
  seq_last   bigint;
  seq_called boolean;
begin
  select profile_id into me from profiles limit 1;
  if me is null then
    raise notice 'no profile to author the probe with — skipped';
    return;
  end if;

  seq := pg_get_serial_sequence('projects', 'project_id');
  execute format('select last_value, is_called from %s', seq) into seq_last, seq_called;

  insert into addresses (address_lot_number, address_street_1, address_suburb,
                         address_state, address_postcode, address_council)
  values ('1', 'Hundredth Street', 'Golden Grove', 'SA', '5125', 'City of Tea Tree Gully')
  returning address_id into a;

  insert into projects (project_original_address_id, project_current_address_id,
                        project_type, project_created_by)
  values (a, a, 'residential', me)
  returning project_id into p;

  update projects set project_job_seq_high_water = 98 where project_id = p;

  for i in 1..3 loop
    insert into jobs (project_id, job_original_address_id, job_current_address_id,
                      job_owning_team, job_created_by)
    values (p, a, a, 'acquisition_development', me);
  end loop;

  select array_agg(job_sequence order by job_sequence::integer)
    into got from jobs where project_id = p;

  if got is distinct from array['99', '100', '101'] then
    raise exception 'the boundary reads wrong: %', got;
  end if;

  if not exists (select 1 from jobs where job_id = p::text || '-100') then
    raise exception 'the hundredth job did not get the number it was issued';
  end if;

  -- And the format below 100 is untouched, which is the half that must NOT change.
  if lpad('7', 2, '0') <> '07' then
    raise exception 'the two-digit pad stopped working';
  end if;

  -- The project takes its jobs with it (jobs cascade from projects, 0028), then the
  -- number it borrowed goes back.
  delete from projects where project_id = p;
  delete from addresses where address_id = a;
  perform setval(seq, seq_last, seq_called);

  raise notice 'ok  a project passes 99 jobs — 99, 100, 101, and 01-99 unchanged';
end $$;
