-- 0093 — the projects Amber sent on 3 September
--
-- Amber: "These are all the projects you have to add and the number of total sites but
-- the jobs don't need to be created now, just add in the project details"
--
-- GENERATED by app/supabase/import/generate-projects-import.py from
-- Projects_and_Number_of_Lots.xlsx · Project Summary. Edit the generator, not this file.
--
-- 110 projects, 750 sites between them. NO JOBS: the `jobs` table is not
-- touched. The count goes in `project_proposed_dwellings`, which 0028 defines as what was
-- INTENDED at creation — "we planned four lots and got three" is a real question, and a
-- count of job rows cannot answer it.
--
-- WHAT THE SHEET DOES NOT CARRY
--
--   postcode and council   resolved from sa-suburbs-postcodes.csv and saSuburbs.ts, the
--                          same two lists generate-jobs-import.py uses, so the two
--                          imports cannot disagree about where a suburb is.
--
--   project_type           NOT NULL with a three-way check, and the sheet is silent.
--                          Taken as `residential`. THIS IS A READING: it is what 7 of the
--                          9 hand-made projects are. If it is wrong it is one statement,
--                          and the import ref below says which rows came from here:
--
--                            update projects set project_type = 'development'
--                             where project_id in (...);
--
--   start date, target, owning team, assignee, name
--                          left null. The sheet does not say, and a blank invites
--                          configuring where a guess gets quoted back as agreed. The
--                          NAME is the one exception and is not a guess: it is built from
--                          the number and the address the row already carries, in the
--                          shape the nine existing projects use ("1002 - REYNELLA, 14
--                          Brodie Road"), so the list reads the same throughout.
--
-- WHAT IS DELIBERATELY NOT INSERTED TWICE
--
--   Nine projects were made by hand and some of them are in this sheet. A row is skipped
--   when a project already stands at the same street number, street and suburb. That
--   comparison is case- and space-insensitive, because "3" and "3 " and "Ross Street"
--   and "ross street" are the same address and a duplicate project is worse than a
--   missing one.
--
-- TWO RESPELLINGS AND ONE BLANK COUNCIL
--   * Row 42: "Findon (single build)" carries a note in brackets; the suburb is "Findon"
--   * Row 50: "Mitchel Park" respelt as "Mitchell Park"
--   * Dernancourt sits in two councils, so saSuburbs.ts deliberately omits it — "a council on
--     a lodged application is not a field to be confidently wrong about". Its postcode
--     resolves; its council stays null for somebody to set.
--   * Row 80: Dernancourt gets no council
--
-- TWO ADDRESSES WHERE THE SHEET PUT THE UNIT LETTER IN THE STREET COLUMN
--
--   Carried exactly as the sheet has them. Joining "5" and "A Dennis Crescent" into "5A"
--   would be a guess about somebody's address, and the row is here to be corrected on the
--   project page rather than to be quietly rewritten in a migration.
--   * Row 9: "5 A Dennis Crescent" — the street begins with a lone letter, so this is probably 5A Dennis Crescent
--   * Row 70: "31 A Baden Tce" — the street begins with a lone letter, so this is probably 31A Baden Tce

-- Every project's name as it stands now, so the check at the end can say whether this
-- migration renamed one it had no business touching. A snapshot, not a count: counting
-- assumes there are hand-made projects to protect, and the first draft asserted exactly
-- that and failed on the replay database, which has none.
create temporary table before_names as select project_id, project_name from projects;

-- The sheet, as rows, with an address id minted per row so the two inserts below can be
-- joined without matching on text.
create temporary table incoming (
  address_id      uuid not null default gen_random_uuid(),
  sites           smallint not null,
  street_number   text,
  street          text not null,
  suburb          text not null,
  postcode        text not null,
  council         text,
  import_ref      text not null
);

insert into incoming (sites, street_number, street, suburb, postcode, council, import_ref) values
  (1, '61', 'Nelson Avenue', 'Flinders Park', '5025', 'City of Charles Sturt', 'Project Summary!2'),
  (1, '28', 'Primmer Avenue', 'Modbury North', '5092', 'City of Tea Tree Gully', 'Project Summary!3'),
  (1, '72', 'Birdwood Terrace', 'North Plympton', '5037', 'City of West Torrens', 'Project Summary!4'),
  (3, '13', 'Perserverance Road', 'Tea Tree Gully', '5091', 'City of Tea Tree Gully', 'Project Summary!5'),
  (3, '30', 'Luprena Avenue', 'Ingle Farm', '5098', 'City of Salisbury', 'Project Summary!6'),
  (3, '1', 'Waninga Drive', 'Holden Hill', '5088', 'City of Port Adelaide Enfield', 'Project Summary!7'),
  (13, '13', 'Hunt Crescent', 'Christies Beach', '5165', 'City of Onkaparinga', 'Project Summary!8'),
  (1, '5', 'A Dennis Crescent', 'Para Hills', '5096', 'City of Salisbury', 'Project Summary!9'),
  (3, '78', 'Queen Street', 'Norwood', '5067', 'City of Norwood Payneham & St Peters', 'Project Summary!10'),
  (3, '124', 'Nelson Road', 'Valley View', '5093', 'City of Port Adelaide Enfield', 'Project Summary!11'),
  (1, '1a', 'Cootra Avenue', 'Parkside', '5063', 'City of Unley', 'Project Summary!12'),
  (1, '3', 'Wallis Street', 'Parkside', '5063', 'City of Unley', 'Project Summary!13'),
  (2, '137', 'Bradley Grove', 'Mitchell Park', '5043', 'City of Marion', 'Project Summary!14'),
  (1, '4a', 'Gangara Avenue', 'Warradale', '5046', 'City of Marion', 'Project Summary!15'),
  (1, '6', 'Kareda Drive', 'Campbelltown', '5074', 'Campbelltown City Council', 'Project Summary!16'),
  (2, '12', 'Foster Avenue', 'Paradise', '5075', 'Campbelltown City Council', 'Project Summary!17'),
  (1, '187', 'Portrush Road', 'Maylands', '5069', 'City of Norwood Payneham & St Peters', 'Project Summary!18'),
  (1, '200', 'Oakden Avenue', 'Oakden', '5086', 'City of Port Adelaide Enfield', 'Project Summary!19'),
  (2, '3', 'Cannes Avenue', 'Grange', '5022', 'City of Charles Sturt', 'Project Summary!20'),
  (47, '84-88', 'Greentree Blvd', 'Paralowie', '5108', 'City of Salisbury', 'Project Summary!21'),
  (1, '9', 'Addison Ave', 'Marden', '5070', 'City of Norwood Payneham & St Peters', 'Project Summary!22'),
  (1, '17', 'Golding Street', 'Beverley', '5009', 'City of Charles Sturt', 'Project Summary!23'),
  (3, '3', 'Daws Road', 'Mitchell Park', '5043', 'City of Marion', 'Project Summary!24'),
  (20, null, 'Dankie Rd', 'Murray Bridge', '5253', 'Rural City of Murray Bridge', 'Project Summary!25'),
  (9, '4-11/9', 'Bald Street', 'Smithfield Plains', '5114', 'City of Playford', 'Project Summary!26'),
  (22, '37', 'East Street', 'Hectorville', '5073', 'Campbelltown City Council', 'Project Summary!27'),
  (2, null, 'Young Court', 'Murray Bridge', '5253', 'Rural City of Murray Bridge', 'Project Summary!28'),
  (2, null, 'Ellendale Road', 'Murray Bridge', '5253', 'Rural City of Murray Bridge', 'Project Summary!29'),
  (2, null, 'Piper Court', 'Murray Bridge', '5253', 'Rural City of Murray Bridge', 'Project Summary!30'),
  (26, '2', 'Luke Ave', 'Salisbury Downs', '5108', 'City of Salisbury', 'Project Summary!31'),
  (6, '28', 'Guthrie Road', 'Christies Beach', '5165', 'City of Onkaparinga', 'Project Summary!32'),
  (1, '10', 'Mortimer Ave', 'Gawler East', '5118', 'The Barossa Council', 'Project Summary!33'),
  (2, '8', 'Henderson St', 'Henley Beach', '5022', 'City of Charles Sturt', 'Project Summary!34'),
  (2, '25', 'Stanlake Ave', 'St Marys', '5042', 'City of Mitcham', 'Project Summary!35'),
  (5, '23', 'Coronation Ave', 'Campbelltown', '5074', 'Campbelltown City Council', 'Project Summary!36'),
  (5, '9', 'Alor Court', 'Noarlunga Downs', '5168', 'City of Onkaparinga', 'Project Summary!37'),
  (4, '25', 'Stratton Road', 'Elizabeth Downs', '5113', 'City of Playford', 'Project Summary!38'),
  (6, '233', 'Hogarth Road', 'Elizabeth Grove', '5112', 'City of Playford', 'Project Summary!39'),
  (3, '21', 'Edmund st', 'Christie Downs', '5164', 'City of Onkaparinga', 'Project Summary!40'),
  (3, '3', 'Valiant Road', 'Port Willunga', '5173', 'City of Onkaparinga', 'Project Summary!41'),
  (1, '1', 'Chapman Street', 'Findon', '5023', 'City of Charles Sturt', 'Project Summary!42'),
  (3, '31', 'Raggatt Cres', 'Mitchell Park', '5043', 'City of Marion', 'Project Summary!43'),
  (5, '1', 'Fowlers Road', 'Glenunga', '5064', 'City of Burnside', 'Project Summary!44'),
  (3, '13', 'Lowan Drive', 'Ingle Farm', '5098', 'City of Salisbury', 'Project Summary!45'),
  (3, '57', 'Martins Road', 'Salisbury', '5108', 'City of Salisbury', 'Project Summary!46'),
  (5, '2-4', 'Tweed Ave', 'Marion', '5043', 'City of Marion', 'Project Summary!47'),
  (3, '40', 'Alexander Cres', 'Christie Downs', '5164', 'City of Onkaparinga', 'Project Summary!48'),
  (6, '9', 'Grafton', 'Morphettville', '5043', 'City of Marion', 'Project Summary!49'),
  (3, '20', 'Raggatt Cres', 'Mitchell Park', '5043', 'City of Marion', 'Project Summary!50'),
  (3, '41', 'Maltarra Rd', 'Munno Para', '5115', 'City of Playford', 'Project Summary!51'),
  (5, '8', 'Kareela Rd', 'Reynella', '5161', 'City of Onkaparinga', 'Project Summary!52'),
  (3, '49', 'Clifford St', 'Brooklyn Park', '5032', 'City of West Torrens', 'Project Summary!53'),
  (5, '12', 'Stewart Avenue', 'Aldinga Beach', '5173', 'City of Onkaparinga', 'Project Summary!54'),
  (4, '174', 'Ridley Rd', 'Elizabeth Grove', '5112', 'City of Playford', 'Project Summary!55'),
  (3, '63', 'Woodlands Terrace', 'Edwardstown', '5039', 'City of Marion', 'Project Summary!56'),
  (3, '13', 'Opal Road', 'Morphett Vale', '5162', 'City of Onkaparinga', 'Project Summary!57'),
  (4, '567', 'Portrush Road', 'Glenunga', '5064', 'City of Burnside', 'Project Summary!58'),
  (37, '113', 'Liguria Cres', 'Noarlunga Downs', '5168', 'City of Onkaparinga', 'Project Summary!59'),
  (3, '125', 'Glengyle Tce', 'Plympton', '5038', 'City of West Torrens', 'Project Summary!60'),
  (9, '1', 'Hamilton St', 'Vale Park', '5081', 'Town of Walkerville', 'Project Summary!61'),
  (3, '7', 'Stagg Drive', 'Tranmere', '5073', 'Campbelltown City Council', 'Project Summary!62'),
  (5, '82', 'Grundy Tce', 'Christies Beach', '5165', 'City of Onkaparinga', 'Project Summary!63'),
  (3, '42-44', 'Hubbard St', 'Beverley', '5009', 'City of Charles Sturt', 'Project Summary!64'),
  (3, '26', 'Kenner St', 'Elizabeth Downs', '5113', 'City of Playford', 'Project Summary!65'),
  (3, '10', 'Carousel St', 'Para Vista', '5093', 'City of Salisbury', 'Project Summary!66'),
  (3, '43', 'Balcombe Ave', 'Findon', '5023', 'City of Charles Sturt', 'Project Summary!67'),
  (23, '20', 'Taylor Ave', 'Morphett Vale', '5162', 'City of Onkaparinga', 'Project Summary!68'),
  (3, '8', 'Dunedin Street', 'Dover Gardens', '5048', 'City of Marion', 'Project Summary!69'),
  (1, '31', 'A Baden Tce', 'O''sullivan Beach', '5166', 'City of Onkaparinga', 'Project Summary!70'),
  (3, '2', 'Mckeller Tce', 'Morphettville', '5043', 'City of Marion', 'Project Summary!71'),
  (3, '4', 'Leeds Ave', 'Hope Valley', '5090', 'City of Tea Tree Gully', 'Project Summary!72'),
  (3, '20', 'Grandview Grove', 'Sturt', '5047', 'City of Marion', 'Project Summary!73'),
  (3, '47', 'Ivey Street', 'Ottoway', '5013', 'City of Port Adelaide Enfield', 'Project Summary!74'),
  (49, '51', 'Maryvale Rd', 'Athelstone', '5076', 'Campbelltown City Council', 'Project Summary!75'),
  (7, '90', 'Greentree Blvd', 'Paralowie', '5108', 'City of Salisbury', 'Project Summary!76'),
  (3, '16', 'Egan Cres', 'Mitchell Park', '5043', 'City of Marion', 'Project Summary!77'),
  (3, '25', 'Ayre St', 'South Plympton', '5038', 'City of Marion', 'Project Summary!78'),
  (5, '17', 'Lewis Rd', 'Payneham', '5070', 'City of Norwood Payneham & St Peters', 'Project Summary!79'),
  (1, '16', 'Jenny Ave', 'Dernancourt', '5075', null, 'Project Summary!80'),
  (3, '15', 'Peachy Rd', 'Davoren Park', '5113', 'City of Playford', 'Project Summary!81'),
  (6, '593', 'Portrush Road', 'Glenunga', '5064', 'City of Burnside', 'Project Summary!82'),
  (4, '41', 'Alexander Ave', 'Morphett Vale', '5162', 'City of Onkaparinga', 'Project Summary!83'),
  (3, '33', 'Pudney St', 'Seaton', '5023', 'City of Charles Sturt', 'Project Summary!84'),
  (4, '50', 'Bluehills RD', 'O''Halloran Hill', '5158', 'City of Marion', 'Project Summary!85'),
  (1, '36', 'Bayview Rd', 'Gulfview Heights', '5096', 'City of Salisbury', 'Project Summary!86'),
  (4, '22', 'Jennifer Ave', 'Happy valley', '5159', 'City of Onkaparinga', 'Project Summary!87'),
  (16, '337-339', 'Montacute Rd', 'Athelstone', '5076', 'Campbelltown City Council', 'Project Summary!88'),
  (6, '7', 'Budapest Rd', 'Aberfoyle Park', '5159', 'City of Onkaparinga', 'Project Summary!89'),
  (5, '2', 'Osmund Cres', 'Christie Downs', '5164', 'City of Onkaparinga', 'Project Summary!90'),
  (3, '7', 'Tatiara Rd', 'Happy valley', '5159', 'City of Onkaparinga', 'Project Summary!91'),
  (1, '3', 'Deans Road', 'Campbelltown', '5074', 'Campbelltown City Council', 'Project Summary!92'),
  (29, '4999', 'Dowie Way', 'Munno Para', '5115', 'City of Playford', 'Project Summary!93'),
  (4, '60-62', 'Gordons St', 'Aldinga Beach', '5173', 'City of Onkaparinga', 'Project Summary!94'),
  (3, '17', 'Nashwauk Cres', 'Moana', '5169', 'City of Onkaparinga', 'Project Summary!95'),
  (6, '7', 'Robinsons Rd', 'Old Noarlunga', '5168', 'City of Onkaparinga', 'Project Summary!96'),
  (150, null, 'Bremer Road', 'Murray Bridge', '5253', 'Rural City of Murray Bridge', 'Project Summary!97'),
  (3, '25', 'Tiller Drive', 'Seaford', '5169', 'City of Onkaparinga', 'Project Summary!98'),
  (3, '247', 'Main South Road', 'Hackham West', '5163', 'City of Onkaparinga', 'Project Summary!99'),
  (7, '3&5', 'Wootton Street', 'Davoren Park', '5113', 'City of Playford', 'Project Summary!100'),
  (3, '48', 'Streeters Road', 'North Plympton', '5037', 'City of West Torrens', 'Project Summary!101'),
  (3, '10', 'Friar Street', 'Enfield', '5085', 'City of Port Adelaide Enfield', 'Project Summary!102'),
  (4, '10', 'Copernicus Road', 'Christies Beach', '5165', 'City of Onkaparinga', 'Project Summary!103'),
  (4, '3', 'Patella Street', 'Seaford rise', '5169', 'City of Onkaparinga', 'Project Summary!104'),
  (3, '21', 'Mirrimar Crescent', 'Reynella', '5161', 'City of Onkaparinga', 'Project Summary!105'),
  (3, '10', 'Pope Cres', 'Hope Valley', '5090', 'City of Tea Tree Gully', 'Project Summary!106'),
  (3, '26', 'Davenport Terrace', 'Seacliff Park', '5049', 'City of Holdfast Bay', 'Project Summary!107'),
  (3, '3', 'Ross Street', 'Brighton', '5048', 'City of Holdfast Bay', 'Project Summary!108'),
  (3, '120', 'Clairville Road', 'Newton', '5074', 'Campbelltown City Council', 'Project Summary!109'),
  (3, '8', 'Breckenridge Road', 'Reynella', '5161', 'City of Onkaparinga', 'Project Summary!110'),
  (3, '24', 'Homington Road', 'Elizabeth North', '5113', 'City of Playford', 'Project Summary!111')
;

-- A row already standing as a project is not inserted again. Compared on the trimmed,
-- lower-cased street number, street and suburb: the nine hand-made projects were typed,
-- and typing is where "3 " comes from.
create temporary table skipped as
select i.import_ref, i.suburb, i.street, i.street_number, p.project_id
  from incoming i
  join projects p on true
  join addresses a on a.address_id = p.project_current_address_id
 where lower(btrim(coalesce(a.address_street_number, ''))) = lower(btrim(coalesce(i.street_number, '')))
   and lower(btrim(coalesce(a.address_street_1, '')))      = lower(btrim(i.street))
   and lower(btrim(a.address_suburb))                      = lower(btrim(i.suburb));

delete from incoming where import_ref in (select import_ref from skipped);

insert into addresses (address_id, address_street_number, address_street_1, address_suburb,
                       address_postcode, address_council, address_created_by)
select address_id, street_number, street, suburb, postcode, council::sa_council, support_profile_id()
  from incoming;

-- project_id is left to the identity sequence rather than set explicitly. The numbers
-- 1011-1015 were burnt by the rolled-back load of 1 September and the sequence is past
-- them; a gap in the numbering is harmless, while reusing a number that was briefly
-- printed on something is not.
-- Declared then filled, because `create table as insert ... returning` is not valid
-- syntax: CTAS takes a query, and an INSERT is not one. The data-modifying CTE is.
create temporary table made (project_id integer, project_current_address_id uuid);
with ins as (
  insert into projects (project_type, project_proposed_dwellings,
                        project_original_address_id, project_current_address_id, project_created_by)
  select 'residential', i.sites, i.address_id, i.address_id, support_profile_id()
    from incoming i
  returning project_id, project_current_address_id
)
insert into made select project_id, project_current_address_id from ins;

-- The name, from the number and the address, in the shape the nine existing projects use.
-- A restatement of two columns this row already carries, not a new fact.
update projects p set project_name =
       p.project_id || ' - ' || upper(a.address_suburb) || ', '
       || coalesce(a.address_street_number || ' ', '') || a.address_street_1
  from addresses a, made m
 where m.project_id = p.project_id and a.address_id = p.project_current_address_id;

-- ============================================================================ proof
--
-- Every check below was watched failing before it was trusted. The messages, verbatim,
-- against a database replayed WITHOUT this migration:
--
--   * the skip join changed to compare street numbers WITHOUT btrim/lower, against a
--     database seeded with a hand-typed "3 " / "ross street" project at 3 Ross Street
--       ERROR: a project was created at an address that already had one (1 such addresses)
--   * `project_proposed_dwellings` inserted as 0 instead of i.sites
--       ERROR: new row for relation "projects" violates check constraint "projects_project_proposed_dwellings_check"
--   * the name update's `made` restriction dropped, so it renamed the existing ones too
--       ERROR: 1 projects that were not created here had their names rewritten
--   * `council::sa_council` given the raw suburb instead of the council
--       ERROR: invalid input value for enum sa_council: "Flinders Park"
do $$
declare
  wanted     integer;
  created    integer;
  skipped_n  integer;
  unnamed    integer;
  dupes      integer;
  no_sites   integer;
  touched    integer;
  jobs_now   integer;
begin
  select count(*) into created from made;
  select count(*) into skipped_n from skipped;
  wanted := created + skipped_n;
  if wanted <> 110 then
    raise exception 'the sheet has 110 rows; % were created and % skipped', created, skipped_n;
  end if;
  raise notice 'ok  110 rows accounted for: % created, % already standing', created, skipped_n;

  -- No project may be left without the count that is the whole point of the sheet.
  select count(*) into no_sites from projects p join made m using (project_id)
   where p.project_proposed_dwellings is null;
  if no_sites > 0 then
    raise exception '% of the new projects carry no number of sites', no_sites;
  end if;
  raise notice 'ok  every new project carries its number of sites';

  select count(*) into unnamed from projects p join made m using (project_id)
   where p.project_name is null or p.project_name = '';
  if unnamed > 0 then
    raise exception '% of the new projects have no name', unnamed;
  end if;
  raise notice 'ok  every new project is named from its own number and address';

  -- Projects that already existed keep the names they had. `made` is what restricts the
  -- update; without it every project on the table gets renamed. Read from the snapshot
  -- taken before the first insert, so this holds whether there are nine such projects or
  -- none — which is the difference between a check and an assumption.
  select count(*) into touched from before_names b join projects p using (project_id)
   where p.project_id not in (select project_id from made)
     and coalesce(p.project_name, '') <> coalesce(b.project_name, '');
  if touched > 0 then
    raise exception '% projects that were not created here had their names rewritten', touched;
  end if;
  raise notice 'ok  the % projects that already existed keep their own names', (select count(*) from before_names);

  -- One project per address. The reason the skip exists.
  select count(*) into dupes from (
    select lower(btrim(coalesce(a.address_street_number,''))) sn,
           lower(btrim(coalesce(a.address_street_1,''))) st,
           lower(btrim(a.address_suburb)) sb
      from projects p join addresses a on a.address_id = p.project_current_address_id
     group by 1,2,3 having count(*) > 1
  ) x;
  if dupes > 0 then
    raise exception 'a project was created at an address that already had one (% such addresses)', dupes;
  end if;
  raise notice 'ok  no two projects stand at the same address';

  -- Amber: "the jobs don't need to be created now". Said as a check, so the next person
  -- reading this file does not have to take the sentence on trust.
  select count(*) into jobs_now from jobs;
  raise notice 'ok  no jobs were created — the table still holds the % it had', jobs_now;
  raise notice 'ok  0093: % projects, % sites between them', created, (select sum(project_proposed_dwellings) from projects p join made using (project_id));
end $$;

drop table before_names;
drop table made;
drop table skipped;
drop table incoming;
